### ISSUE TITLE
Add Typescript definitions

### ISSUE THREAD

**Issue by moberemk** [dialogflow/dialogflow-nodejs-client-v2#10]
This is less of a bug and more of a feature request; adding typescript definitions would make this library far easier to work with for Typescript users. JSDoc is nice, but code completion support with that is spotty.

**Comment by CharlesT100** [comment]
This would be really great, just in case another comment helps!

**Comment by peternann** [comment]
+100. Typescript rocks. The non-typescript-javascript world don't realise what they are missing...

**Comment by beeme1mr** [comment]
Has there been any progress on this?  I've started making my own but it doesn't cover everything yet.

**Comment by miguelsilv** [comment]
@beeme1mr  Could you make yours available?

**Comment by dyladan** [comment]
@moberemk @CharlesT100 @peternann @miguelsilv DefinitelyTyped/DefinitelyTyped#27899

It may not be merged because it isn't tested and it doesn't _completely_ cover the package. (batch style calls and callback style calls are not in the typings) but it is a great start if you want to make a PR against my copy (dyladan/DefinitelyTyped) to help add these things. If not, I'll get to them when I have time.

**Comment by dyladan** [comment]
@moberemk you can probably close this ticket now. Looks like the dialogflow team doesn't hardly even look at these let alone keep them cleaned up.

**Comment by moberemk** [comment]
Unfortunately true... @beccca  pinging you because this seems like it would be a dev relations question, should this be closed or is it better to leave it open as a potentially to-be-addressed feature request?

**Comment by JustinBeckwith** [comment]
Greetings folks!  It looks like the types are merged in definitely typed, so I'm going to go ahead and close this one out :) Please do let me know if y'all have any questions!

**Comment by JustinBeckwith** [comment]
Got it.  We're much more likely to rewrite the library in TypeScript, so I filed #153 to track it!

**Comment by moberemk** [comment]
That makes sense, thanks for clarifying!
