### ISSUE TITLE
Support for batchDelete

### ISSUE THREAD

**Issue by brandon-pereira** [dialogflow/dialogflow-nodejs-client-v2#111]
Hey there!

I was wondering if you currently have support for batchDeleting of intents, and if not if you were planning on adding it.

https://dialogflow.com/docs/reference/api-v2/rest/v2/projects.agent.intents/batchDelete

If you do, I'm more than happy to add documentation for it.

NOTE: This is for intents, but also supported in the API is Entity and EntityTypes.

Let me know if I can help!

Thanks!

**Comment by brandon-pereira** [comment]
I figured it out!

For those who find this, it's

```
      this.IntentsClient.batchDeleteIntents({
        parent: this.ProjectAgentPath,
        languageCode: this.lang,
        intents // intents being an array as returned from listIntents
      })
```

**Comment by bigman73** [comment]
I'm looking at index.t.ts (version 0.7.0) and see this:
        // TODO: add batch style calls
        // batchUpdateIntents(request: BatchUpdateIntentsRequest): void;
        // batchDeleteIntents(request: BatchDeleteIntentsRequest): void;


How did you get the APIs to work with the npm module if they're not implemented?
