### ISSUE TITLE
High Memory Consumption if sending audio files 

### ISSUE THREAD

**Issue by roxor1909** [dialogflow/dialogflow-nodejs-client-v2#119]
I detect a very high Memory Consumption in my backend. I sent audio files and text querys to my backend, which sends it do Dialogflow using the npm package. 

#### Environment details
  - OS: CentOS 7
  - Node.js version: 8.11.1
  - npm version: 6.1
  - `dialogflow` version: 0.5.0

#### Steps to reproduce
I used the following Function to send a audio file to DF:

function detectAudioIntent(  projectId,  sessionId,  filename,  encoding,  sampleRateHertz,  languageCode,  resToClient) {
  const dialogflow = require('dialogflow');
  const sessionClient = new dialogflow.SessionsClient();

  const sessionPath = sessionClient.sessionPath(projectId, sessionId);
  const readFile = common.util.promisify(fs.readFile, { singular: true });
  readFile(filename)
    .then(inputAudio => {
      const request = {
        session: sessionPath,
        queryInput: {
          audioConfig: {
            audioEncoding: encoding,
            sampleRateHertz: sampleRateHertz,
            languageCode: languageCode,
          },
        },
        inputAudio: inputAudio,
      };
      return sessionClient.detectIntent(request);
    })
    .then(responses => {
      const response = responses[0];
      response.sessionId = sessionId;
      resToClient.send(response);
      fs.unlink(filename, function(error) {
        if(error){ 
          console.log(error);
          throw error;
        }
      });
    })
    .catch(err => {     
      resToClient.status(400).send(err.details);
    });
}

2) start your service with pm2
3) send audio files to your Server which handles the connection to Dialogflow
4) monitor your backend with pm2 monit backend => then you can see the memory consumption of your backend

How do you implement it? Anyone else has the same problem?

Regards 
Robin

**Comment by jrash06** [comment]
Do you close the audio file after sending it? Maybe it's a memory leak somewhere in the code.

**Comment by roxor1909** [comment]
No, I delete it afterwards. And I didn't use a FileDiskriptor because I didn't send it as stream. I use readFile and this didn't create a stream:
const readFile = common.util.promisify(fs.readFile, { singular: true });
readFile(filename)
