### ISSUE TITLE
Unable to create training phrases with type: 'TYPE_TEMPALTE'

### ISSUE THREAD

**Issue by pusmax** [dialogflow/dialogflow-nodejs-client-v2#130]
#### Environment details

  - OS: Ubuntu
  - Node.js version: 10.6.0
  - npm version: 6.1.0
  - `dialogflow` version: 0.50

#### Steps to reproduce

  1. Define Intent with template trainingPhrases :   [{
    type: 'TYPE_TEMPLATE',
    parts: [{text: "I'd like a @size:size pizza"}],
  }]
  2. Create defined Intent: intentsClient.createIntent(Intent)
  3. When define intent with training phrases type: 'TYPE_TEMPLATE' it's still created like type: 
    'TYPE_EXAMPLE'. 
  4. Also this example from github doesn't set training phrase like template: 
   https://github.com/dialogflow/dialogflow-nodejs-client-v2/blob/master/samples/resource.js#L397

Please help me with this case.
Thank you.

**Comment by madongfly** [comment]
Hi Max, I'm trying to reproduce this, a few questions:

1. Could you please paste the whole content of the intent you were trying to create?
2. For your step 3, how did you verified the training phrase was created as "TYPE_EXAMPLE"? checking through the UI?
3. For your step 4, I don't follow, why did you mean by "the example from github doesn't set training phrase like template"?

Thanks,

**Comment by pusmax** [comment]
2. Yes, through the UI.
1, 3. If you execute this example(https://github.com/dialogflow/dialogflow-nodejs-client-v2/blob/master/samples/resource.js#L397) It doesn't create template trainingPhrase, although in code specifies type: 'TYPE_TEMPLATE'.

**Comment by madongfly** [comment]
Thanks Max!

Turned out it's a bug that the example is not synced with our protos: https://dialogflow.com/docs/reference/api-v2/rest/Shared.Types/Type

The enum name has been changed to "TEMPLATE" but the example hasn't been updated.

We'll fix it, thanks for the reporting and sorry for the troubles!
