### ISSUE TITLE
Not able to detect audio Intent

### ISSUE THREAD

**Issue by axchanda** [dialogflow/dialogflow-nodejs-client-v2#54]
Whenever I try to send audio to detect Intent by editing the detect.js code with nessecary values: 
{ sample Rate = 16000, encoding: 'AUDIO_ENCODING_LINEAR16', file is PCM file. I always get INVALID_ARGUMENT: While calling Cloud Speech API: Invalid recognition 'config': bad encoding.. Can you please help on this. I tried with stackflow, no fruitful solutions. Please help me immediately on this. Thanks!

**Comment by tefrati** [comment]
Same thing here. Seem like a the wrong write function is called..

**Comment by lukaszbk** [comment]
The encoding name is AUDIO_ENCODING_LINEAR_16, not AUDIO_ENCODING_LINEAR16 (note the underscore between LINEAR and 16).

**Comment by axchanda** [comment]
@lukaszbk  Thanks for the solution. It worked! Also, please change that in your code too. Might be helpful for others too....
@tefrati It works dude.... Follow the above mentioned solution.
