### ISSUE TITLE
Import to Angular 6 Project

### ISSUE THREAD

**Issue by roxor1909** [dialogflow/dialogflow-nodejs-client-v2#85]
Hey,
it is possible to import the npm module dialogflow-nodejs-client-v2 to an angular project? Can I also use features like the Google Cloud Speech service?

Thanks for your answer!

**Comment by madongfly** [comment]
I don't know about Angular but I "guess" the answer should be yes for your first question.

I didn't get your second question, are you asking whether you can call Speech service with this client library? if so, the answer is no, Dialogflow and Cloud Speech are two different apis with different client libraries.

**Comment by roxor1909** [comment]
Thank you for your answers!
@madongfly  I read that you can use the Google Speech api in Dialogflow v2 for speech-to-text conversation.
@Ploppy3  I get the same errors.

**Comment by madongfly** [comment]
You can pass the audio directly to Dialogflow for querying, Dialogflow will convert it to text.

**Comment by madongfly** [comment]
Hi guys, what's the Dialogflow library version you used? can you find the missing .js file using ls? we are trying to reproduce it.
Thanks,

**Comment by Ploppy3** [comment]
@madongfly `"dialogflow": "0.4.0"`
How can I install "nodejs lib" ?

**Comment by Ploppy3** [comment]
@madongfly 
![image](https://user-images.githubusercontent.com/7990765/40199399-9b8c6a4c-5a19-11e8-9e43-cc44767e6120.png)

Please note that I'm installing with yarn.

**Comment by roxor1909** [comment]
@madongfly 
How should I pass it directly to Dialogflow without using the node-js client?

**Comment by madongfly** [comment]
@roxor1909
By "directly",  I meant you don't need to call Cloud-Speech-to-Text API, instead, just calling Dialogflow api (through the Dialogflow client).

**Comment by Ploppy3** [comment]
@madongfly any news?

**Comment by roxor1909** [comment]
You can't integrate it directly to your angular project. 
You need to write your own node.js Rest service and there you can use this package.

**Comment by Ploppy3** [comment]
@roxor1909 I don't think that's how you are supposed to do it.

**Comment by roxor1909** [comment]
I didn't know any other solution. 
I think the name is Client libaray because your Rest Service is the clint of Dialogflow.

**Comment by ballwood** [comment]
@roxor1909,

You might have some luck with the implementation in googleapis as they use axios which is client side and are REST only, try this code below:

````
'use strict';

const {google} = require('googleapis');
const path = require('path');

async function runSample () {

  const client = await google.auth.getClient({
    keyFile: path.join(__dirname, 'key.json'),
    scopes: 'https://www.googleapis.com/auth/cloud-platform'
  });

  const dialogflow = google.dialogflow({
    version: 'v2',
    auth: client
  });

  const result = await dialogflow.projects.getAgent({
    parent: 'projects/<your-project-id>'
  });

  console.log(result.data);

}

if (module === require.main) {
  runSample().catch(console.error);
}

// Exports for unit testing purposes
module.exports = { runSample };
````

**Comment by roxor1909** [comment]
Ty @ballwood 
I decided too use this package on server side. So I started to implement my own node.js Server. 

The docu is really bad :(

**Comment by DipakMahapurkar** [comment]
Hi All, I am developing Chatbot Mobile Application with Ionic V3 and Dialog Flow v2, please share any sample code or any example for integration of Dialog flow for text, audio, event request?

Thanks in advance.
