### ISSUE TITLE
Where should I use this library?

### ISSUE THREAD

**Issue by roxor1909** [dialogflow/dialogflow-nodejs-client-v2#86]
Hey,
I am a bit confused about the name of this library. Where did I use this library? On client side where my web frontend is shown (Smartphone, tablet, computer) or on my backend server (centos etc.)? 

Thanks in advance!

**Comment by madongfly** [comment]
The "client" in the name is relative to the Dialogflow server, it's the "client library" used to talk to Dialogflow server, so using it on your "client" or "server" side, is totally up to you.

**Comment by roxor1909** [comment]
But I can't use it on my smartphone (client) because it's an node.js package which is normally used in backend. I don't know if browserify supports this package and I can used it on this client. 

My idea is the following: I record the voice in my frontend, send it to my own node.js backend (which uses this npm package). This backend sends this audio file to dialogflow which processes the data and sends the response back.  Is this the right place to use this package?

**Comment by madongfly** [comment]
I was answering you question in a general perspective, not related to concrete environments. :)

You idea sounds good to me.

**Comment by Ploppy3** [comment]
@madongfly why would you drop front end Javascript support, why make it much more complicated? Too many people used it? I was one of those person, quick example, now my only solution is drop this feature since I can't use it while relying only on Firebase.

**Comment by htasha** [comment]
I also don't understand how and where to use this library, as @roxor1909 said

> My idea is the following: I record the voice in my frontend, send it to my own node.js backend (which uses this npm package). This backend sends this audio file to dialogflow which processes the data and sends the response back. Is this the right place to use this package?

I was thinking about configuring my agent through Dialogflow, build my own bot interface/chat box with some js framework and just call the agent with user queries.

I don't want to embed the default Dialogflow interface: https://dialogflow.com/docs/sdks I wanted to build my own.

How should I use this: https://dialogflow.com/docs/reference/api-v2/rest

**Comment by roxor1909** [comment]
I used it in my own node.js backend. It is working.
